In [1]:
# PRABAL GHOSH LAB-6 

import re
import nltk
file1=open('C:/Users/Prabal Ghosh/Desktop/text_lab5.txt',encoding="utf8",errors='ignore')

In [2]:
input_text=(file1.read()).lower()   #normalization to lower case

In [3]:
print(input_text)


# text pre processing is started from here 

pattern = '@+[0-9]{8}\s<(p|h)>|<(p|h)>|@+'
result_text = re.sub(pattern,'',input_text)
result_text


@@31553641 <p> the government last july called the energy sector debt situation a " state of emergency . " <p> this was during the mid-year budget review during which the finance minister ken ofori-atta castigated the previous ndc government for entering into " obnoxious take-or-pay contracts signed by the ndc , which obligate us to pay for capacity we do not need . " <p> the government pays over gh ? 2.5 billion annually for some 2,300mw in installed capacity which the country does not consume . <p> he sounded alarmed that " from 2020 if nothing is done , we will be facing annual excess gas capacity charges of between $550 and $850 million every year . <p> joynews ' business editor george wiafe said the latest imf staff report expressing fears over a possible classification is " more of a warning " to government . <p> he said the latest assessment raises concerns about the purpose of government borrowings , whether it goes into consumption or into projects capable of generating reven

'\n the government last july called the energy sector debt situation a " state of emergency . "  this was during the mid-year budget review during which the finance minister ken ofori-atta castigated the previous ndc government for entering into " obnoxious take-or-pay contracts signed by the ndc , which obligate us to pay for capacity we do not need . "  the government pays over gh ? 2.5 billion annually for some 2,300mw in installed capacity which the country does not consume .  he sounded alarmed that " from 2020 if nothing is done , we will be facing annual excess gas capacity charges of between $550 and $850 million every year .  joynews \' business editor george wiafe said the latest imf staff report expressing fears over a possible classification is " more of a warning " to government .  he said the latest assessment raises concerns about the purpose of government borrowings , whether it goes into consumption or into projects capable of generating revenue to pay back the loan . 

In [4]:
import nltk
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
print(stop_words)          #stopword list

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [5]:
from nltk.tokenize import word_tokenize  

In [6]:
word_tokens = word_tokenize(result_text)   #word tokes

In [7]:
print(word_tokens)

['the', 'government', 'last', 'july', 'called', 'the', 'energy', 'sector', 'debt', 'situation', 'a', '``', 'state', 'of', 'emergency', '.', '``', 'this', 'was', 'during', 'the', 'mid-year', 'budget', 'review', 'during', 'which', 'the', 'finance', 'minister', 'ken', 'ofori-atta', 'castigated', 'the', 'previous', 'ndc', 'government', 'for', 'entering', 'into', '``', 'obnoxious', 'take-or-pay', 'contracts', 'signed', 'by', 'the', 'ndc', ',', 'which', 'obligate', 'us', 'to', 'pay', 'for', 'capacity', 'we', 'do', 'not', 'need', '.', '``', 'the', 'government', 'pays', 'over', 'gh', '?', '2.5', 'billion', 'annually', 'for', 'some', '2,300mw', 'in', 'installed', 'capacity', 'which', 'the', 'country', 'does', 'not', 'consume', '.', 'he', 'sounded', 'alarmed', 'that', '``', 'from', '2020', 'if', 'nothing', 'is', 'done', ',', 'we', 'will', 'be', 'facing', 'annual', 'excess', 'gas', 'capacity', 'charges', 'of', 'between', '$', '550', 'and', '$', '850', 'million', 'every', 'year', '.', 'joynews', "

In [8]:
another_list = ['@','<','p','>','``','?',':','$','31553641','!','#','%','&'] 
new_stop_words=stop_words.extend(another_list)
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [9]:
new_list=list()
for word in word_tokens:
    if word.lower() not in stop_words:                     #stopword removal
        new_list.append(word)
print(new_list)
        

['government', 'last', 'july', 'called', 'energy', 'sector', 'debt', 'situation', 'state', 'emergency', '.', 'mid-year', 'budget', 'review', 'finance', 'minister', 'ken', 'ofori-atta', 'castigated', 'previous', 'ndc', 'government', 'entering', 'obnoxious', 'take-or-pay', 'contracts', 'signed', 'ndc', ',', 'obligate', 'us', 'pay', 'capacity', 'need', '.', 'government', 'pays', 'gh', '2.5', 'billion', 'annually', '2,300mw', 'installed', 'capacity', 'country', 'consume', '.', 'sounded', 'alarmed', '2020', 'nothing', 'done', ',', 'facing', 'annual', 'excess', 'gas', 'capacity', 'charges', '550', '850', 'million', 'every', 'year', '.', 'joynews', "'", 'business', 'editor', 'george', 'wiafe', 'said', 'latest', 'imf', 'staff', 'report', 'expressing', 'fears', 'possible', 'classification', 'warning', 'government', '.', 'said', 'latest', 'assessment', 'raises', 'concerns', 'purpose', 'government', 'borrowings', ',', 'whether', 'goes', 'consumption', 'projects', 'capable', 'generating', 'revenue

In [10]:
vocabulary1 = []
for w in new_list:
    if w.lower() not in vocabulary1:
        vocabulary1.append(w.lower())
vocabulary1

['government',
 'last',
 'july',
 'called',
 'energy',
 'sector',
 'debt',
 'situation',
 'state',
 'emergency',
 '.',
 'mid-year',
 'budget',
 'review',
 'finance',
 'minister',
 'ken',
 'ofori-atta',
 'castigated',
 'previous',
 'ndc',
 'entering',
 'obnoxious',
 'take-or-pay',
 'contracts',
 'signed',
 ',',
 'obligate',
 'us',
 'pay',
 'capacity',
 'need',
 'pays',
 'gh',
 '2.5',
 'billion',
 'annually',
 '2,300mw',
 'installed',
 'country',
 'consume',
 'sounded',
 'alarmed',
 '2020',
 'nothing',
 'done',
 'facing',
 'annual',
 'excess',
 'gas',
 'charges',
 '550',
 '850',
 'million',
 'every',
 'year',
 'joynews',
 "'",
 'business',
 'editor',
 'george',
 'wiafe',
 'said',
 'latest',
 'imf',
 'staff',
 'report',
 'expressing',
 'fears',
 'possible',
 'classification',
 'warning',
 'assessment',
 'raises',
 'concerns',
 'purpose',
 'borrowings',
 'whether',
 'goes',
 'consumption',
 'projects',
 'capable',
 'generating',
 'revenue',
 'back',
 'loan',
 'move',
 'could',
 'increase',

In [11]:
import numpy as np

In [12]:
#One-hot encoding
a = []
i = 0
for w in vocabulary1:
    t = np.zeros(len(vocabulary1), dtype = np.int16)
    t[i] = 1
    a.append(t)
    i = i + 1 
i=0
for e in a:
    print(vocabulary1[i],'-->', e)
    i=i+1

government --> [1 0 0 ... 0 0 0]
last --> [0 1 0 ... 0 0 0]
july --> [0 0 1 ... 0 0 0]
called --> [0 0 0 ... 0 0 0]
energy --> [0 0 0 ... 0 0 0]
sector --> [0 0 0 ... 0 0 0]
debt --> [0 0 0 ... 0 0 0]
situation --> [0 0 0 ... 0 0 0]
state --> [0 0 0 ... 0 0 0]
emergency --> [0 0 0 ... 0 0 0]
. --> [0 0 0 ... 0 0 0]
mid-year --> [0 0 0 ... 0 0 0]
budget --> [0 0 0 ... 0 0 0]
review --> [0 0 0 ... 0 0 0]
finance --> [0 0 0 ... 0 0 0]
minister --> [0 0 0 ... 0 0 0]
ken --> [0 0 0 ... 0 0 0]
ofori-atta --> [0 0 0 ... 0 0 0]
castigated --> [0 0 0 ... 0 0 0]
previous --> [0 0 0 ... 0 0 0]
ndc --> [0 0 0 ... 0 0 0]
entering --> [0 0 0 ... 0 0 0]
obnoxious --> [0 0 0 ... 0 0 0]
take-or-pay --> [0 0 0 ... 0 0 0]
contracts --> [0 0 0 ... 0 0 0]
signed --> [0 0 0 ... 0 0 0]
, --> [0 0 0 ... 0 0 0]
obligate --> [0 0 0 ... 0 0 0]
us --> [0 0 0 ... 0 0 0]
pay --> [0 0 0 ... 0 0 0]
capacity --> [0 0 0 ... 0 0 0]
need --> [0 0 0 ... 0 0 0]
pays --> [0 0 0 ... 0 0 0]
gh --> [0 0 0 ... 0 0 0]
2.5 --> [0

era --> [0 0 0 ... 0 0 0]
gamut --> [0 0 0 ... 0 0 0]
including --> [0 0 0 ... 0 0 0]
redevelopment --> [0 0 0 ... 0 0 0]
critical --> [0 0 0 ... 0 0 0]
water --> [0 0 0 ... 0 0 0]
supply --> [0 0 0 ... 0 0 0]
initiatives --> [0 0 0 ... 0 0 0]
serve --> [0 0 0 ... 0 0 0]
populations --> [0 0 0 ... 0 0 0]
arid --> [0 0 0 ... 0 0 0]
areas --> [0 0 0 ... 0 0 0]
nation --> [0 0 0 ... 0 0 0]
developed --> [0 0 0 ... 0 0 0]
partnerships --> [0 0 0 ... 0 0 0]
stakeholders --> [0 0 0 ... 0 0 0]
locally --> [0 0 0 ... 0 0 0]
saturday --> [0 0 0 ... 0 0 0]
popular --> [0 0 0 ... 0 0 0]
jazz --> [0 0 0 ... 0 0 0]
singer --> [0 0 0 ... 0 0 0]
gananath --> [0 0 0 ... 0 0 0]
dasanayaka --> [0 0 0 ... 0 0 0]
band --> [0 0 0 ... 0 0 0]
en --> [0 0 0 ... 0 0 0]
route --> [0 0 0 ... 0 0 0]
set --> [0 0 0 ... 0 0 0]
mood --> [0 0 0 ... 0 0 0]
evening --> [0 0 0 ... 0 0 0]
good --> [0 0 0 ... 0 0 0]
owsc --> [0 0 0 ... 0 0 0]
atmosphere --> [0 0 0 ... 0 0 0]
wining --> [0 0 0 ... 0 0 0]
dining --> [0 0 0 

gere --> [0 0 0 ... 0 0 0]
rosamund --> [0 0 0 ... 0 0 0]
pike --> [0 0 0 ... 0 0 0]
long --> [0 0 0 ... 0 0 0]
list --> [0 0 0 ... 0 0 0]
major --> [0 0 0 ... 0 0 0]
immortals --> [0 0 0 ... 0 0 0]
total --> [0 0 0 ... 0 0 0]
recall --> [0 0 0 ... 0 0 0]
maze --> [0 0 0 ... 0 0 0]
runner --> [0 0 0 ... 0 0 0]
death --> [0 0 0 ... 0 0 0]
cure --> [0 0 0 ... 0 0 0]
shutdown --> [0 0 0 ... 0 0 0]
funding --> [0 0 0 ... 0 0 0]
border --> [0 0 0 ... 0 0 0]
wall --> [0 0 0 ... 0 0 0]
largely --> [0 0 0 ... 0 0 0]
disabled --> [0 0 0 ... 0 0 0]
system --> [0 0 0 ... 0 0 0]
immigration --> [0 0 0 ... 0 0 0]
cases --> [0 0 0 ... 0 0 0]
courts --> [0 0 0 ... 0 0 0]
overburdened --> [0 0 0 ... 0 0 0]
delayed --> [0 0 0 ... 0 0 0]
indefinitely --> [0 0 0 ... 0 0 0]
judge --> [0 0 0 ... 0 0 0]
dana --> [0 0 0 ... 0 0 0]
leigh --> [0 0 0 ... 0 0 0]
marks --> [0 0 0 ... 0 0 0]
former --> [0 0 0 ... 0 0 0]
president --> [0 0 0 ... 0 0 0]
association --> [0 0 0 ... 0 0 0]
judges --> [0 0 0 ... 0 0 0]


things --> [0 0 0 ... 0 0 0]
extra --> [0 0 0 ... 0 0 0]
sordid --> [0 0 0 ... 0 0 0]
80 --> [0 0 0 ... 0 0 0]
families --> [0 0 0 ... 0 0 0]
however --> [0 0 0 ... 0 0 0]
vacation --> [0 0 0 ... 0 0 0]
hit --> [0 0 0 ... 0 0 0]
embassy --> [0 0 0 ... 0 0 0]
application --> [0 0 0 ... 0 0 0]
land --> [0 0 0 ... 0 0 0]
aircraft --> [0 0 0 ... 0 0 0]
airlift --> [0 0 0 ... 0 0 0]
32 --> [0 0 0 ... 0 0 0]
statement --> [0 0 0 ... 0 0 0]
extremely --> [0 0 0 ... 0 0 0]
wary --> [0 0 0 ... 0 0 0]
relaxing --> [0 0 0 ... 0 0 0]
concerned --> [0 0 0 ... 0 0 0]
threat --> [0 0 0 ... 0 0 0]
breaking --> [0 0 0 ... 0 0 0]
quarantine --> [0 0 0 ... 0 0 0]
zone --> [0 0 0 ... 0 0 0]
placed --> [0 0 0 ... 0 0 0]
18 --> [0 0 0 ... 0 0 0]
56 --> [0 0 0 ... 0 0 0]
matters --> [0 0 0 ... 0 0 0]
worse --> [0 0 0 ... 0 0 0]
mayor --> [0 0 0 ... 0 0 0]
5 --> [0 0 0 ... 0 0 0]
holiday --> [0 0 0 ... 0 0 0]
authorities --> [0 0 0 ... 0 0 0]
warned --> [0 0 0 ... 0 0 0]
spread --> [0 0 0 ... 0 0 0]
even --> 

emergence --> [0 0 0 ... 0 0 0]
antibiotic-resistant --> [0 0 0 ... 0 0 0]
dying --> [0 0 0 ... 0 0 0]
last-resort --> [0 0 0 ... 0 0 0]
really --> [0 0 0 ... 0 0 0]
discover --> [0 0 0 ... 0 0 0]
happen --> [0 0 0 ... 0 0 0]
citation --> [0 0 0 ... 0 0 0]
retrieved --> [0 0 0 ... 0 0 0]
26 --> [0 0 0 ... 0 0 0]
https --> [0 0 0 ... 0 0 0]
* --> [0 0 0 ... 0 0 0]
39 --> [0 0 0 ... 0 0 0]
1197 --> [0 0 0 ... 0 0 0]
toolong --> [0 0 0 ... 0 0 0]
document --> [0 0 0 ... 0 0 0]
subject --> [0 0 0 ... 0 0 0]
copyright --> [0 0 0 ... 0 0 0]
apart --> [0 0 0 ... 0 0 0]
fair --> [0 0 0 ... 0 0 0]
dealing --> [0 0 0 ... 0 0 0]
reproduced --> [0 0 0 ... 0 0 0]
written --> [0 0 0 ... 0 0 0]
information --> [0 0 0 ... 0 0 0]
purposes --> [0 0 0 ... 0 0 0]
e-mail --> [0 0 0 ... 0 0 0]
story --> [0 0 0 ... 0 0 0]
recipient --> [0 0 0 ... 0 0 0]
sent --> [0 0 0 ... 0 0 0]
email --> [0 0 0 ... 0 0 0]
neither --> [0 0 0 ... 0 0 0]
address --> [0 0 0 ... 0 0 0]
enter --> [0 0 0 ... 0 0 0]
message --> [0

june --> [0 0 0 ... 0 0 0]
1967 --> [0 0 0 ... 0 0 0]
civic --> [0 0 0 ... 0 0 0]
tns --> [0 0 0 ... 0 0 0]
little --> [0 0 0 ... 0 0 0]
checklist --> [0 0 0 ... 0 0 0]
item --> [0 0 0 ... 0 0 0]
ca --> [0 0 0 ... 0 0 0]
seem --> [0 0 0 ... 0 0 0]
nailed --> [0 0 0 ... 0 0 0]
slam --> [0 0 0 ... 0 0 0]
answers --> [0 0 0 ... 0 0 0]
knows --> [0 0 0 ... 0 0 0]
thing --> [0 0 0 ... 0 0 0]
thrives --> [0 0 0 ... 0 0 0]
active --> [0 0 0 ... 0 0 0]
researcher --> [0 0 0 ... 0 0 0]
northwestern --> [0 0 0 ... 0 0 0]
feinberg --> [0 0 0 ... 0 0 0]
school --> [0 0 0 ... 0 0 0]
turned --> [0 0 0 ... 0 0 0]
old --> [0 0 0 ... 0 0 0]
causes --> [0 0 0 ... 0 0 0]
coined --> [0 0 0 ... 0 0 0]
circumstantial --> [0 0 0 ... 0 0 0]
1960s --> [0 0 0 ... 0 0 0]
control --> [0 0 0 ... 0 0 0]
program --> [0 0 0 ... 0 0 0]
aimed --> [0 0 0 ... 0 0 0]
educating --> [0 0 0 ... 0 0 0]
bringing --> [0 0 0 ... 0 0 0]
issues --> [0 0 0 ... 0 0 0]
grapples --> [0 0 0 ... 0 0 0]
availability --> [0 0 0 ... 0 0 0]

trust --> [0 0 0 ... 0 0 0]
stumps --> [0 0 0 ... 0 0 0]
calls --> [0 0 0 ... 0 0 0]
flicked --> [0 0 0 ... 0 0 0]
glove --> [0 0 0 ... 0 0 0]
fow --> [0 0 0 ... 0 0 0]
76 --> [0 0 0 ... 0 0 0]
eng --> [0 0 0 ... 0 0 0]
212/2 --> [0 0 0 ... 0 0 0]
57 --> [0 0 0 ... 0 0 0]
maharaj --> [0 0 0 ... 0 0 0]
replaced --> [0 0 0 ... 0 0 0]
pretorius --> [0 0 0 ... 0 0 0]
prods --> [0 0 0 ... 0 0 0]
towards --> [0 0 0 ... 0 0 0]
carves --> [0 0 0 ... 0 0 0]
away --> [0 0 0 ... 0 0 0]
backward --> [0 0 0 ... 0 0 0]
convert --> [0 0 0 ... 0 0 0]
half-centuries --> [0 0 0 ... 0 0 0]
love --> [0 0 0 ... 0 0 0]
push --> [0 0 0 ... 0 0 0]
204/2 --> [0 0 0 ... 0 0 0]
82 --> [0 0 0 ... 0 0 0]
52 --> [0 0 0 ... 0 0 0]
low --> [0 0 0 ... 0 0 0]
rumbles --> [0 0 0 ... 0 0 0]
rooooooooooooot --> [0 0 0 ... 0 0 0]
captain --> [0 0 0 ... 0 0 0]
glides --> [0 0 0 ... 0 0 0]
half-century --> [0 0 0 ... 0 0 0]
sweep --> [0 0 0 ... 0 0 0]
impressive --> [0 0 0 ... 0 0 0]
knock --> [0 0 0 ... 0 0 0]
shake --> [0 

8/0 --> [0 0 0 ... 0 0 0]
kelvin --> [0 0 0 ... 0 0 0]
grove --> [0 0 0 ... 0 0 0]
thunders --> [0 0 0 ... 0 0 0]
strokes --> [0 0 0 ... 0 0 0]
leg-side --> [0 0 0 ... 0 0 0]
talk --> [0 0 0 ... 0 0 0]
nerve-settler --> [0 0 0 ... 0 0 0]
sensibly --> [0 0 0 ... 0 0 0]
leaving --> [0 0 0 ... 0 0 0]
confidence-booster --> [0 0 0 ... 0 0 0]
newbie --> [0 0 0 ... 0 0 0]
eeeek --> [0 0 0 ... 0 0 0]
undone --> [0 0 0 ... 0 0 0]
squirts --> [0 0 0 ... 0 0 0]
narrowly --> [0 0 0 ... 0 0 0]
missing --> [0 0 0 ... 0 0 0]
223 --> [0 0 0 ... 0 0 0]
trail --> [0 0 0 ... 0 0 0]
whatever --> [0 0 0 ... 0 0 0]
ate --> [0 0 0 ... 0 0 0]
breakfast --> [0 0 0 ... 0 0 0]
trick --> [0 0 0 ... 0 0 0]
dismissed --> [0 0 0 ... 0 0 0]
hour --> [0 0 0 ... 0 0 0]
fit --> [0 0 0 ... 0 0 0]
5-40 --> [0 0 0 ... 0 0 0]
driving --> [0 0 0 ... 0 0 0]
seat --> [0 0 0 ... 0 0 0]
ben --> [0 0 0 ... 0 0 0]
slip-catcher --> [0 0 0 ... 0 0 0]
extraordinaire --> [0 0 0 ... 0 0 0]
becomes --> [0 0 0 ... 0 0 0]
catches --> [0 

stephen --> [0 0 0 ... 0 0 0]
brown --> [0 0 0 ... 0 0 0]
thinking --> [0 0 0 ... 0 0 0]
western --> [0 0 0 ... 0 0 0]
liberal --> [0 0 0 ... 0 0 0]
seeing --> [0 0 0 ... 0 0 0]
double --> [0 0 0 ... 0 0 0]
philanthropic --> [0 0 0 ... 0 0 0]
colleges --> [0 0 0 ... 0 0 0]
europe --> [0 0 0 ... 0 0 0]
expand --> [0 0 0 ... 0 0 0]
verbatim --> [0 0 0 ... 0 0 0]
russia --> [0 0 0 ... 0 0 0]
actual --> [0 0 0 ... 0 0 0]
would-be --> [0 0 0 ... 0 0 0]
dictators --> [0 0 0 ... 0 0 0]
easier --> [0 0 0 ... 0 0 0]
events --> [0 0 0 ... 0 0 0]
rule --> [0 0 0 ... 0 0 0]
taker --> [0 0 0 ... 0 0 0]
sajid --> [0 0 0 ... 0 0 0]
javid --> [0 0 0 ... 0 0 0]
boris --> [0 0 0 ... 0 0 0]
johnson --> [0 0 0 ... 0 0 0]
ban --> [0 0 0 ... 0 0 0]
sipping --> [0 0 0 ... 0 0 0]
champagne --> [0 0 0 ... 0 0 0]
billionaires --> [0 0 0 ... 0 0 0]
drinking --> [0 0 0 ... 0 0 0]
coffee --> [0 0 0 ... 0 0 0]
rather --> [0 0 0 ... 0 0 0]
bubbly --> [0 0 0 ... 0 0 0]
chancellor --> [0 0 0 ... 0 0 0]
tight --> [0 0 

pleased --> [0 0 0 ... 0 0 0]
picture --> [0 0 0 ... 0 0 0]
lenny --> [0 0 0 ... 0 0 0]
kravitz --> [0 0 0 ... 0 0 0]
fan --> [0 0 0 ... 0 0 0]
salesforce --> [0 0 0 ... 0 0 0]
iii --> [0 0 0 ... 0 0 0]
dancing --> [0 0 0 ... 0 0 0]
stars --> [0 0 0 ... 0 0 0]
personality --> [0 0 0 ... 0 0 0]
julianne --> [0 0 0 ... 0 0 0]
hough --> [0 0 0 ... 0 0 0]
exorcism --> [0 0 0 ... 0 0 0]
raided --> [0 0 0 ... 0 0 0]
tried --> [0 0 0 ... 0 0 0]
cloudflare --> [0 0 0 ... 0 0 0]
party --> [0 0 0 ... 0 0 0]
derulo --> [0 0 0 ... 0 0 0]
solomon --> [0 0 0 ... 0 0 0]
goldman --> [0 0 0 ... 0 0 0]
sachs --> [0 0 0 ... 0 0 0]
dj-ed --> [0 0 0 ... 0 0 0]
moncler --> [0 0 0 ... 0 0 0]
jacket --> [0 0 0 ... 0 0 0]
spied --> [0 0 0 ... 0 0 0]
texting --> [0 0 0 ... 0 0 0]
journalists --> [0 0 0 ... 0 0 0]
tell --> [0 0 0 ... 0 0 0]
firmwide --> [0 0 0 ... 0 0 0]
mandate --> [0 0 0 ... 0 0 0]
interconnected --> [0 0 0 ... 0 0 0]
themes --> [0 0 0 ... 0 0 0]
inclusive --> [0 0 0 ... 0 0 0]
helping --> [0 

responding --> [0 0 0 ... 0 0 0]
geo-political --> [0 0 0 ... 0 0 0]
conceded --> [0 0 0 ... 0 0 0]
divided --> [0 0 0 ... 0 0 0]
conflict --> [0 0 0 ... 0 0 0]
libya --> [0 0 0 ... 0 0 0]
division --> [0 0 0 ... 0 0 0]
hesitation --> [0 0 0 ... 0 0 0]
weekend --> [0 0 0 ... 0 0 0]
ceasefire --> [0 0 0 ... 0 0 0]
direction --> [0 0 0 ... 0 0 0]
strongly --> [0 0 0 ... 0 0 0]
reconciliation --> [0 0 0 ... 0 0 0]
reconstruction --> [0 0 0 ... 0 0 0]
quotable --> [0 0 0 ... 0 0 0]
fragile --> [0 0 0 ... 0 0 0]
true --> [0 0 0 ... 0 0 0]
lies --> [0 0 0 ... 0 0 0]
pieces --> [0 0 0 ... 0 0 0]
instructed --> [0 0 0 ... 0 0 0]
exception --> [0 0 0 ... 0 0 0]
skip --> [0 0 0 ... 0 0 0]
negotiations --> [0 0 0 ... 0 0 0]
declaration --> [0 0 0 ... 0 0 0]
define --> [0 0 0 ... 0 0 0]
unite --> [0 0 0 ... 0 0 0]
access --> [0 0 0 ... 0 0 0]
quote --> [0 0 0 ... 0 0 0]
choice --> [0 0 0 ... 0 0 0]
distant --> [0 0 0 ... 0 0 0]
distance --> [0 0 0 ... 0 0 0]
mic --> [0 0 0 ... 0 0 0]
spanish --> [

god --> [0 0 0 ... 0 0 0]
committing --> [0 0 0 ... 0 0 0]
plant --> [0 0 0 ... 0 0 0]
teen --> [0 0 0 ... 0 0 0]
kicked --> [0 0 0 ... 0 0 0]
ticket --> [0 0 0 ... 0 0 0]
woman --> [0 0 0 ... 0 0 0]
livestream --> [0 0 0 ... 0 0 0]
ladies --> [0 0 0 ... 0 0 0]
gonzales --> [0 0 0 ... 0 0 0]
meetings --> [0 0 0 ... 0 0 0]
commissioner --> [0 0 0 ... 0 0 0]
phil --> [0 0 0 ... 0 0 0]
hogan --> [0 0 0 ... 0 0 0]
internal --> [0 0 0 ... 0 0 0]
thierry --> [0 0 0 ... 0 0 0]
breton --> [0 0 0 ... 0 0 0]
possibly --> [0 0 0 ... 0 0 0]
joint --> [0 0 0 ... 0 0 0]
musketeers --> [0 0 0 ... 0 0 0]
seeking --> [0 0 0 ... 0 0 0]
settle --> [0 0 0 ... 0 0 0]
spat --> [0 0 0 ... 0 0 0]
emmanuel --> [0 0 0 ... 0 0 0]
tweeting --> [0 0 0 ... 0 0 0]
discussion --> [0 0 0 ... 0 0 0]
sentiment --> [0 0 0 ... 0 0 0]
postpone --> [0 0 0 ... 0 0 0]
elisa --> [0 0 0 ... 0 0 0]
braun --> [0 0 0 ... 0 0 0]
pledged --> [0 0 0 ... 0 0 0]
retaliatory --> [0 0 0 ... 0 0 0]
tariffs --> [0 0 0 ... 0 0 0]
tuned --> 

equalizing --> [0 0 0 ... 0 0 0]
anyway --> [0 0 0 ... 0 0 0]
gelles --> [0 0 0 ... 0 0 0]
punchline --> [0 0 0 ... 0 0 0]
quotes --> [0 0 0 ... 0 0 0]
eurasia --> [0 0 0 ... 0 0 0]
ian --> [0 0 0 ... 0 0 0]
bremmer --> [0 0 0 ... 0 0 0]
easily --> [0 0 0 ... 0 0 0]
intensity --> [0 0 0 ... 0 0 0]
bill --> [0 0 0 ... 0 0 0]
gates --> [0 0 0 ... 0 0 0]
notable --> [0 0 0 ... 0 0 0]
absentee --> [0 0 0 ... 0 0 0]
shifted --> [0 0 0 ... 0 0 0]
smoke --> [0 0 0 ... 0 0 0]
straining --> [0 0 0 ... 0 0 0]
tobacco --> [0 0 0 ... 0 0 0]
sensitive --> [0 0 0 ... 0 0 0]
element --> [0 0 0 ... 0 0 0]
sponsorship --> [0 0 0 ... 0 0 0]
rival --> [0 0 0 ... 0 0 0]
nine-time --> [0 0 0 ... 0 0 0]
grammy --> [0 0 0 ... 0 0 0]
winner --> [0 0 0 ... 0 0 0]
artist --> [0 0 0 ... 0 0 0]
beverley --> [0 0 0 ... 0 0 0]
knight --> [0 0 0 ... 0 0 0]
auto-schwab --> [0 0 0 ... 0 0 0]
airing --> [0 0 0 ... 0 0 0]
filmmaker --> [0 0 0 ... 0 0 0]
marcus --> [0 0 0 ... 0 0 0]
vetter --> [0 0 0 ... 0 0 0]
scenes --

streets --> [0 0 0 ... 0 0 0]
below-freezing --> [0 0 0 ... 0 0 0]
-15 --> [0 0 0 ... 0 0 0]
degrees --> [0 0 0 ... 0 0 0]
fahrenheit --> [0 0 0 ... 0 0 0]
entrepreneur --> [0 0 0 ... 0 0 0]
campaigns --> [0 0 0 ... 0 0 0]
skills --> [0 0 0 ... 0 0 0]
contrast --> [0 0 0 ... 0 0 0]
somewhere --> [0 0 0 ... 0 0 0]
stays --> [0 0 0 ... 0 0 0]
trek --> [0 0 0 ... 0 0 0]
fancy-ville --> [0 0 0 ... 0 0 0]
behold --> [0 0 0 ... 0 0 0]
managing --> [0 0 0 ... 0 0 0]
monck --> [0 0 0 ... 0 0 0]
glamorous --> [0 0 0 ... 0 0 0]
pro --> [0 0 0 ... 0 0 0]
tip --> [0 0 0 ... 0 0 0]
besides --> [0 0 0 ... 0 0 0]
sensible --> [0 0 0 ... 0 0 0]
shoes --> [0 0 0 ... 0 0 0]
wear --> [0 0 0 ... 0 0 0]
layers --> [0 0 0 ... 0 0 0]
concession --> [0 0 0 ... 0 0 0]
sweater --> [0 0 0 ... 0 0 0]
faux-fur-lined --> [0 0 0 ... 0 0 0]
hood --> [0 0 0 ... 0 0 0]
boots --> [0 0 0 ... 0 0 0]
alone --> [0 0 0 ... 0 0 0]
impress --> [0 0 0 ... 0 0 0]
anyone --> [0 0 0 ... 0 0 0]
tone-deaf --> [0 0 0 ... 0 0 0]
chill

appearances --> [0 0 0 ... 0 0 0]
compared --> [0 0 0 ... 0 0 0]
venezuelan --> [0 0 0 ... 0 0 0]
populist --> [0 0 0 ... 0 0 0]
strongman --> [0 0 0 ... 0 0 0]
returned --> [0 0 0 ... 0 0 0]
insult --> [0 0 0 ... 0 0 0]
accusing --> [0 0 0 ... 0 0 0]
trio --> [0 0 0 ... 0 0 0]
sixth --> [0 0 0 ... 0 0 0]
sardine --> [0 0 0 ... 0 0 0]
squeezing --> [0 0 0 ... 0 0 0]
alternative --> [0 0 0 ... 0 0 0]
wopke --> [0 0 0 ... 0 0 0]
hoekstra --> [0 0 0 ... 0 0 0]
worries --> [0 0 0 ... 0 0 0]
vote --> [0 0 0 ... 0 0 0]
speaks --> [0 0 0 ... 0 0 0]
electronic --> [0 0 0 ... 0 0 0]
waste --> [0 0 0 ... 0 0 0]
silver --> [0 0 0 ... 0 0 0]
e-waste --> [0 0 0 ... 0 0 0]
momentum --> [0 0 0 ... 0 0 0]
single-use --> [0 0 0 ... 0 0 0]
plastics --> [0 0 0 ... 0 0 0]
invested --> [0 0 0 ... 0 0 0]
adult --> [0 0 0 ... 0 0 0]
smoking --> [0 0 0 ... 0 0 0]
advancement --> [0 0 0 ... 0 0 0]
robust --> [0 0 0 ... 0 0 0]
harnessing --> [0 0 0 ... 0 0 0]
alternatives --> [0 0 0 ... 0 0 0]
cigarettes --> [0

opec+ --> [0 0 0 ... 0 0 0]
output --> [0 0 0 ... 0 0 0]
december --> [0 0 0 ... 0 0 0]
cement --> [0 0 0 ... 0 0 0]
nasty --> [0 0 0 ... 0 0 0]
flux --> [0 0 0 ... 0 0 0]
albeit --> [0 0 0 ... 0 0 0]
unlikely --> [0 0 0 ... 0 0 0]
refunds --> [0 0 0 ... 0 0 0]
stateside --> [0 0 0 ... 0 0 0]
lippman --> [0 0 0 ... 0 0 0]
taxpayer --> [0 0 0 ... 0 0 0]
dollars --> [0 0 0 ... 0 0 0]
americans --> [0 0 0 ... 0 0 0]
tab --> [0 0 0 ... 0 0 0]
jared --> [0 0 0 ... 0 0 0]
kushner --> [0 0 0 ... 0 0 0]
2.9 --> [0 0 0 ... 0 0 0]
feedback --> [0 0 0 ... 0 0 0]
dhl --> [0 0 0 ... 0 0 0]
frank --> [0 0 0 ... 0 0 0]
appel --> [0 0 0 ... 0 0 0]
globalizers --> [0 0 0 ... 0 0 0]
connectedness --> [0 0 0 ... 0 0 0]
noise --> [0 0 0 ... 0 0 0]
expanded --> [0 0 0 ... 0 0 0]
kaminski --> [0 0 0 ... 0 0 0]
ubs --> [0 0 0 ... 0 0 0]
sabine --> [0 0 0 ... 0 0 0]
keller-busse --> [0 0 0 ... 0 0 0]
samans --> [0 0 0 ... 0 0 0]
lippo --> [0 0 0 ... 0 0 0]
riady --> [0 0 0 ... 0 0 0]
crash --> [0 0 0 ... 0 0 

insead --> [0 0 0 ... 0 0 0]
communications --> [0 0 0 ... 0 0 0]
adecco --> [0 0 0 ... 0 0 0]
competitiveness --> [0 0 0 ... 0 0 0]
gtci --> [0 0 0 ... 0 0 0]
ranks --> [0 0 0 ... 0 0 0]
125 --> [0 0 0 ... 0 0 0]
114 --> [0 0 0 ... 0 0 0]
high-income --> [0 0 0 ... 0 0 0]
switzerland --> [0 0 0 ... 0 0 0]
tops --> [0 0 0 ... 0 0 0]
denmark --> [0 0 0 ... 0 0 0]
3,000 --> [0 0 0 ... 0 0 0]
wef-goers --> [0 0 0 ... 0 0 0]
spillover --> [0 0 0 ... 0 0 0]
canton --> [0 0 0 ... 0 0 0]
graub --> [0 0 0 ... 0 0 0]
nden --> [0 0 0 ... 0 0 0]
2.25 --> [0 0 0 ... 0 0 0]
1.125 --> [0 0 0 ... 0 0 0]
3.375 --> [0 0 0 ... 0 0 0]
correction --> [0 0 0 ... 0 0 0]
employer --> [0 0 0 ... 0 0 0]
trusted --> [0 0 0 ... 0 0 0]
institution --> [0 0 0 ... 0 0 0]
48 --> [0 0 0 ... 0 0 0]
89-year --> [0 0 0 ... 0 0 0]
fatality --> [0 0 0 ... 0 0 0]
human-to-human --> [0 0 0 ... 0 0 0]
transmission --> [0 0 0 ... 0 0 0]
traveled --> [0 0 0 ... 0 0 0]
persons --> [0 0 0 ... 0 0 0]
image --> [0 0 0 ... 0 0 0]
r

noting --> [0 0 0 ... 0 0 0]
exploded --> [0 0 0 ... 0 0 0]
instant --> [0 0 0 ... 0 0 0]
messenger --> [0 0 0 ... 0 0 0]
telegram --> [0 0 0 ... 0 0 0]
channels --> [0 0 0 ... 0 0 0]
demanded --> [0 0 0 ... 0 0 0]
destruction --> [0 0 0 ... 0 0 0]
railway --> [0 0 0 ... 0 0 0]
roads --> [0 0 0 ... 0 0 0]
linking --> [0 0 0 ... 0 0 0]
culprits --> [0 0 0 ... 0 0 0]
unknown --> [0 0 0 ... 0 0 0]
incidents --> [0 0 0 ... 0 0 0]
chp --> [0 0 0 ... 0 0 0]
victims --> [0 0 0 ... 0 0 0]
mounting --> [0 0 0 ... 0 0 0]
yeung --> [0 0 0 ... 0 0 0]
yun-hung --> [0 0 0 ... 0 0 0]
suspended --> [0 0 0 ... 0 0 0]
frets --> [0 0 0 ... 0 0 0]
fallout --> [0 0 0 ... 0 0 0]
unveil --> [0 0 0 ... 0 0 0]
proposals --> [0 0 0 ... 0 0 0]
unveiled --> [0 0 0 ... 0 0 0]
hongkongers --> [0 0 0 ... 0 0 0]
requests --> [0 0 0 ... 0 0 0]
chan --> [0 0 0 ... 0 0 0]
mo-po --> [0 0 0 ... 0 0 0]
long-standing --> [0 0 0 ... 0 0 0]
arrange --> [0 0 0 ... 0 0 0]
closed-door --> [0 0 0 ... 0 0 0]
newly-added --> [0 0 0

1,200 --> [0 0 0 ... 0 0 0]
kilograms --> [0 0 0 ... 0 0 0]
earn --> [0 0 0 ... 0 0 0]
7.2 --> [0 0 0 ... 0 0 0]
l/100 --> [0 0 0 ... 0 0 0]
onto --> [0 0 0 ... 0 0 0]
bang --> [0 0 0 ... 0 0 0]
buck --> [0 0 0 ... 0 0 0]
loaded --> [0 0 0 ... 0 0 0]
23,398 --> [0 0 0 ... 0 0 0]
18,298 --> [0 0 0 ... 0 0 0]
21,298 --> [0 0 0 ... 0 0 0]
presentation-ready --> [0 0 0 ... 0 0 0]
copies --> [0 0 0 ... 0 0 0]
toronto --> [0 0 0 ... 0 0 0]
star --> [0 0 0 ... 0 0 0]
inquire --> [0 0 0 ... 0 0 0]
permissions/licensing --> [0 0 0 ... 0 0 0]
700 --> [0 0 0 ... 0 0 0]
iceberg --> [0 0 0 ... 0 0 0]
unfolds --> [0 0 0 ... 0 0 0]
eve --> [0 0 0 ... 0 0 0]
travellers --> [0 0 0 ... 0 0 0]
enhanced --> [0 0 0 ... 0 0 0]
airports --> [0 0 0 ... 0 0 0]
montreal --> [0 0 0 ... 0 0 0]
kamran --> [0 0 0 ... 0 0 0]
st. --> [0 0 0 ... 0 0 0]
micheal --> [0 0 0 ... 0 0 0]
originated --> [0 0 0 ... 0 0 0]
evolved --> [0 0 0 ... 0 0 0]
capability --> [0 0 0 ... 0 0 0]
jan. --> [0 0 0 ... 0 0 0]
person-to-perso

admission --> [0 0 0 ... 0 0 0]
neurosurgery --> [0 0 0 ... 0 0 0]
registrar --> [0 0 0 ... 0 0 0]
ms --> [0 0 0 ... 0 0 0]
apparent --> [0 0 0 ... 0 0 0]
unwilling --> [0 0 0 ... 0 0 0]
admit --> [0 0 0 ... 0 0 0]
error --> [0 0 0 ... 0 0 0]
identificationshe --> [0 0 0 ... 0 0 0]
disclose --> [0 0 0 ... 0 0 0]
identity --> [0 0 0 ... 0 0 0]
ends --> [0 0 0 ... 0 0 0]
5a --> [0 0 0 ... 0 0 0]
houses --> [0 0 0 ... 0 0 0]
trauma --> [0 0 0 ... 0 0 0]
fractures --> [0 0 0 ... 0 0 0]
tags --> [0 0 0 ... 0 0 0]
gowns --> [0 0 0 ... 0 0 0]
identification --> [0 0 0 ... 0 0 0]
appears --> [0 0 0 ... 0 0 0]
waits --> [0 0 0 ... 0 0 0]
follows --> [0 0 0 ... 0 0 0]
files --> [0 0 0 ... 0 0 0]
carry --> [0 0 0 ... 0 0 0]
unconscious --> [0 0 0 ... 0 0 0]
anonymity --> [0 0 0 ... 0 0 0]
sensitivity --> [0 0 0 ... 0 0 0]
label --> [0 0 0 ... 0 0 0]
tallied --> [0 0 0 ... 0 0 0]
stoppedthe --> [0 0 0 ... 0 0 0]
realised --> [0 0 0 ... 0 0 0]
mistake --> [0 0 0 ... 0 0 0]
swollen --> [0 0 0 ... 0 

queues --> [0 0 0 ... 0 0 0]
terminus --> [0 0 0 ... 0 0 0]
fianna --> [0 0 0 ... 0 0 0]
martin --> [0 0 0 ... 0 0 0]
preliminary --> [0 0 0 ... 0 0 0]
speculated --> [0 0 0 ... 0 0 0]
simon --> [0 0 0 ... 0 0 0]
postponed --> [0 0 0 ... 0 0 0]
gathers --> [0 0 0 ... 0 0 0]
extra.ie --> [0 0 0 ... 0 0 0]
frontrunning --> [0 0 0 ... 0 0 0]
tenerife --> [0 0 0 ... 0 0 0]
browsing --> [0 0 0 ... 0 0 0]
edit --> [0 0 0 ... 0 0 0]
settings --> [0 0 0 ... 0 0 0]
page --> [0 0 0 ... 0 0 0]
boe --> [0 0 0 ... 0 0 0]
stint --> [0 0 0 ... 0 0 0]
guiding --> [0 0 0 ... 0 0 0]
fortnight --> [0 0 0 ... 0 0 0]
volatility --> [0 0 0 ... 0 0 0]
reading --> [0 0 0 ... 0 0 0]
weakness --> [0 0 0 ... 0 0 0]
retail --> [0 0 0 ... 0 0 0]
-0.6 --> [0 0 0 ... 0 0 0]
-0.3 --> [0 0 0 ... 0 0 0]
-1.2 --> [0 0 0 ... 0 0 0]
flurry --> [0 0 0 ... 0 0 0]
dovish --> [0 0 0 ... 0 0 0]
mpc --> [0 0 0 ... 0 0 0]
saunders --> [0 0 0 ... 0 0 0]
silvana --> [0 0 0 ... 0 0 0]
tenreyro --> [0 0 0 ... 0 0 0]
gertjan --> [0 0

positively --> [0 0 0 ... 0 0 0]
equipped --> [0 0 0 ... 0 0 0]
upgrades --> [0 0 0 ... 0 0 0]
oriented --> [0 0 0 ... 0 0 0]
curtailing --> [0 0 0 ... 0 0 0]
strides --> [0 0 0 ... 0 0 0]
cater --> [0 0 0 ... 0 0 0]
pia-xi/ --> [0 0 0 ... 0 0 0]
caro --> [0 0 0 ... 0 0 0]
bulletins --> [0 0 0 ... 0 0 0]
pcoo --> [0 0 0 ... 0 0 0]
entities --> [0 0 0 ... 0 0 0]
programs --> [0 0 0 ... 0 0 0]
filipino --> [0 0 0 ... 0 0 0]
hospitalised --> [0 0 0 ... 0 0 0]
southwestern --> [0 0 0 ... 0 0 0]
bordeaux --> [0 0 0 ... 0 0 0]
buzyn --> [0 0 0 ... 0 0 0]
sos --> [0 0 0 ... 0 0 0]
medecins --> [0 0 0 ... 0 0 0]
insulated --> [0 0 0 ... 0 0 0]
800 --> [0 0 0 ... 0 0 0]
alarm --> [0 0 0 ... 0 0 0]
declaring --> [0 0 0 ... 0 0 0]
suspecting --> [0 0 0 ... 0 0 0]
climbs --> [0 0 0 ... 0 0 0]
440 --> [0 0 0 ... 0 0 0]
dated --> [0 0 0 ... 0 0 0]
1/23/2020 --> [0 0 0 ... 0 0 0]
12:56:15 --> [0 0 0 ... 0 0 0]
patient.the --> [0 0 0 ... 0 0 0]
compares --> [0 0 0 ... 0 0 0]
originated.a --> [0 0 0 ..

-ism --> [0 0 0 ... 0 0 0]
degrading --> [0 0 0 ... 0 0 0]
person.be --> [0 0 0 ... 0 0 0]
proactive --> [0 0 0 ... 0 0 0]
comment --> [0 0 0 ... 0 0 0]
abusive --> [0 0 0 ... 0 0 0]
posts.share --> [0 0 0 ... 0 0 0]
eyewitness --> [0 0 0 ... 0 0 0]
geovoni --> [0 0 0 ... 0 0 0]
tasha --> [0 0 0 ... 0 0 0]
bucher --> [0 0 0 ... 0 0 0]
bake --> [0 0 0 ... 0 0 0]
outdoor --> [0 0 0 ... 0 0 0]
warms --> [0 0 0 ... 0 0 0]
passenger --> [0 0 0 ... 0 0 0]
two-vehicle --> [0 0 0 ... 0 0 0]
3:39 --> [0 0 0 ... 0 0 0]
2011 --> [0 0 0 ... 0 0 0]
toyota --> [0 0 0 ... 0 0 0]
van --> [0 0 0 ... 0 0 0]
rear-ended --> [0 0 0 ... 0 0 0]
1996 --> [0 0 0 ... 0 0 0]
gmc --> [0 0 0 ... 0 0 0]
pickup --> [0 0 0 ... 0 0 0]
umf --> [0 0 0 ... 0 0 0]
showcases --> [0 0 0 ... 0 0 0]
madness --> [0 0 0 ... 0 0 0]
farmington --> [0 0 0 ... 0 0 0]
emery --> [0 0 0 ... 0 0 0]
arts --> [0 0 0 ... 0 0 0]
showcased --> [0 0 0 ... 0 0 0]
artwork --> [0 0 0 ... 0 0 0]
lobbies --> [0 0 0 ... 0 0 0]
hallways --> [0 0 0 

drivetime --> [0 0 0 ... 0 0 0]
fanatics --> [0 0 0 ... 0 0 0]
peterson --> [0 0 0 ... 0 0 0]
andrew --> [0 0 0 ... 0 0 0]
downs --> [0 0 0 ... 0 0 0]
nut --> [0 0 0 ... 0 0 0]
sean --> [0 0 0 ... 0 0 0]
kcci --> [0 0 0 ... 0 0 0]
12:30 --> [0 0 0 ... 0 0 0]
55-year-old --> [0 0 0 ... 0 0 0]
waited --> [0 0 0 ... 0 0 0]
superior --> [0 0 0 ... 0 0 0]
arrests --> [0 0 0 ... 0 0 0]
robbers --> [0 0 0 ... 0 0 0]
cellphone --> [0 0 0 ... 0 0 0]
punched --> [0 0 0 ... 0 0 0]
duo --> [0 0 0 ... 0 0 0]
backpack --> [0 0 0 ... 0 0 0]
parking --> [0 0 0 ... 0 0 0]
frankfort --> [0 0 0 ... 0 0 0]
bloodied --> [0 0 0 ... 0 0 0]
ear --> [0 0 0 ... 0 0 0]
vincent --> [0 0 0 ... 0 0 0]
parkersburg --> [0 0 0 ... 0 0 0]
ymca --> [0 0 0 ... 0 0 0]
w.va --> [0 0 0 ... 0 0 0]
wtap --> [0 0 0 ... 0 0 0]
1:21 --> [0 0 0 ... 0 0 0]
four-door --> [0 0 0 ... 0 0 0]
driver-side --> [0 0 0 ... 0 0 0]
airbag --> [0 0 0 ... 0 0 0]
deployed --> [0 0 0 ... 0 0 0]
front-end --> [0 0 0 ... 0 0 0]
wood --> [0 0 0 ...

barred --> [0 0 0 ... 0 0 0]
categories --> [0 0 0 ... 0 0 0]
volatile --> [0 0 0 ... 0 0 0]
behavior --> [0 0 0 ... 0 0 0]
unpredictably --> [0 0 0 ... 0 0 0]
cosmic --> [0 0 0 ... 0 0 0]
jekyll --> [0 0 0 ... 0 0 0]
dense --> [0 0 0 ... 0 0 0]
remnant --> [0 0 0 ... 0 0 0]
supernova --> [0 0 0 ... 0 0 0]
sunlike --> [0 0 0 ... 0 0 0]
chandra --> [0 0 0 ... 0 0 0]
x-ray --> [0 0 0 ... 0 0 0]
observatory --> [0 0 0 ... 0 0 0]
karl --> [0 0 0 ... 0 0 0]
f. --> [0 0 0 ... 0 0 0]
jansky --> [0 0 0 ... 0 0 0]
vla --> [0 0 0 ... 0 0 0]
astronomers --> [0 0 0 ... 0 0 0]
binary --> [0 0 0 ... 0 0 0]
switches --> [0 0 0 ... 0 0 0]
egos --> [0 0 0 ... 0 0 0]
insane --> [0 0 0 ... 0 0 0]
depressing --> [0 0 0 ... 0 0 0]
hire --> [0 0 0 ... 0 0 0]
23-year-old --> [0 0 0 ... 0 0 0]
bacon --> [0 0 0 ... 0 0 0]
mcentee --> [0 0 0 ... 0 0 0]
two-day --> [0 0 0 ... 0 0 0]
lucrative --> [0 0 0 ... 0 0 0]
toured --> [0 0 0 ... 0 0 0]
shielded --> [0 0 0 ... 0 0 0]
anti-muslim --> [0 0 0 ... 0 0 0]
dead 

yards --> [0 0 0 ... 0 0 0]
catchment --> [0 0 0 ... 0 0 0]
foreground --> [0 0 0 ... 0 0 0]
barriers --> [0 0 0 ... 0 0 0]
swept --> [0 0 0 ... 0 0 0]
reopening --> [0 0 0 ... 0 0 0]
portland --> [0 0 0 ... 0 0 0]
kptv --> [0 0 0 ... 0 0 0]
reopened --> [0 0 0 ... 0 0 0]
cleared --> [0 0 0 ... 0 0 0]
closures --> [0 0 0 ... 0 0 0]
utilized --> [0 0 0 ... 0 0 0]
barnes --> [0 0 0 ... 0 0 0]
skyline --> [0 0 0 ... 0 0 0]
clearing --> [0 0 0 ... 0 0 0]
daytime --> [0 0 0 ... 0 0 0]
80-foot --> [0 0 0 ... 0 0 0]
comprised --> [0 0 0 ... 0 0 0]
ditches --> [0 0 0 ... 0 0 0]
proceeded --> [0 0 0 ... 0 0 0]
stabilized --> [0 0 0 ... 0 0 0]
oklahomans --> [0 0 0 ... 0 0 0]
oklahoma --> [0 0 0 ... 0 0 0]
osdh --> [0 0 0 ... 1 0 0]
criteria --> [0 0 0 ... 0 1 0]
soap --> [0 0 0 ... 0 0 1]


In [13]:
str1=" ".join(vocabulary1)



In [14]:
str1

"government last july called energy sector debt situation state emergency . mid-year budget review finance minister ken ofori-atta castigated previous ndc entering obnoxious take-or-pay contracts signed , obligate us pay capacity need pays gh 2.5 billion annually 2,300mw installed country consume sounded alarmed 2020 nothing done facing annual excess gas charges 550 850 million every year joynews ' business editor george wiafe said latest imf staff report expressing fears possible classification warning assessment raises concerns purpose borrowings whether goes consumption projects capable generating revenue back loan move could increase 's risk profile ability borrow international market issue another eurobond wants return raise 3bn expenditure items fund domestic sources spend 86m projecting 67bn leaves deficit 19bn monies make available planned seventh time past eight years ghana already among 10 low-income countries ( lics ) africa high distress april 2019 successfully completion e

In [15]:
# PRE PROCESSING FOR BagofWords

from nltk import sent_tokenize
import re
documents = sent_tokenize(result_text)
documents = [word.replace('\n','') for word in documents]
print(documents)
print("No of sentences: ",len(documents))

[' the government last july called the energy sector debt situation a " state of emergency . "', 'this was during the mid-year budget review during which the finance minister ken ofori-atta castigated the previous ndc government for entering into " obnoxious take-or-pay contracts signed by the ndc , which obligate us to pay for capacity we do not need . "', 'the government pays over gh ?', '2.5 billion annually for some 2,300mw in installed capacity which the country does not consume .', 'he sounded alarmed that " from 2020 if nothing is done , we will be facing annual excess gas capacity charges of between $550 and $850 million every year .', 'joynews \' business editor george wiafe said the latest imf staff report expressing fears over a possible classification is " more of a warning " to government .', 'he said the latest assessment raises concerns about the purpose of government borrowings , whether it goes into consumption or into projects capable of generating revenue to pay back

In [16]:
#BagofWords
docV = []
for doc in documents:
    dt = np.zeros(len(vocabulary1))
    for w in doc.split():
        if w.lower() in vocabulary1:
            indexOfW = vocabulary1.index(w.lower())
            dt[indexOfW] +=1
    docV.append(dt)

In [17]:
for d in docV:
    print(d)

[1. 1. 1. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[2. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0.

[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 1. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0.

[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 1. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0.

[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0.

[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0.

[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 1. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0.

[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 1. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 1. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 1. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0.

[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 1. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 1. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0.

In [18]:
# c. Create BoW vectorization for each documents

In [19]:
import sklearn

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
BoWvectorizer = CountVectorizer() 
BoWvectorizer = CountVectorizer(stop_words= 'english')

In [22]:
BoWvectorizer.fit(documents)

CountVectorizer(stop_words='english')

In [23]:
BoWvectorizer.vocabulary_

{'government': 3973,
 'july': 4935,
 'called': 1496,
 'energy': 3127,
 'sector': 7837,
 'debt': 2512,
 'situation': 8078,
 'state': 8367,
 'emergency': 3080,
 'mid': 5679,
 'year': 9774,
 'budget': 1416,
 'review': 7517,
 'finance': 3563,
 'minister': 5717,
 'ken': 4975,
 'ofori': 6172,
 'atta': 865,
 'castigated': 1604,
 'previous': 6847,
 'ndc': 5937,
 'entering': 3157,
 'obnoxious': 6118,
 'pay': 6445,
 'contracts': 2212,
 'signed': 8039,
 'obligate': 6114,
 'capacity': 1546,
 'need': 5948,
 'pays': 6450,
 'gh': 3888,
 'billion': 1166,
 'annually': 678,
 '300mw': 162,
 'installed': 4667,
 'country': 2305,
 'does': 2844,
 'consume': 2170,
 'sounded': 8217,
 'alarmed': 558,
 '2020': 114,
 'facing': 3404,
 'annual': 677,
 'excess': 3295,
 'gas': 3827,
 'charges': 1732,
 '550': 228,
 '850': 287,
 'million': 5695,
 'joynews': 4917,
 'business': 1461,
 'editor': 3010,
 'george': 3874,
 'wiafe': 9627,
 'said': 7690,
 'latest': 5126,
 'imf': 4476,
 'staff': 8332,
 'report': 7391,
 'expressi

In [24]:
BoWvectorizer.get_feature_names()

['000',
 '003490',
 '01',
 '01190902',
 '021',
 '03',
 '032',
 '040',
 '04008957',
 '0500',
 '0517400',
 '06',
 '073',
 '08',
 '09099140121',
 '09099140122',
 '091810',
 '10',
 '100',
 '10005',
 '100m',
 '101',
 '1020',
 '104',
 '109',
 '11',
 '110',
 '111',
 '113',
 '1131',
 '114',
 '114059',
 '117',
 '118',
 '1197',
 '11th',
 '12',
 '120',
 '122',
 '125',
 '128',
 '12pm',
 '12th',
 '13',
 '130',
 '131',
 '1320',
 '133',
 '14',
 '140',
 '141',
 '144',
 '1460',
 '147',
 '15',
 '150',
 '155',
 '156',
 '158',
 '1590',
 '15kg',
 '16',
 '163',
 '165',
 '17',
 '170',
 '176',
 '18',
 '184',
 '186',
 '187',
 '19',
 '1911',
 '1919',
 '1920s',
 '1928',
 '1940',
 '1947',
 '1949',
 '195355',
 '1960s',
 '1965',
 '1966',
 '1967',
 '1969',
 '1972',
 '1973',
 '198',
 '1980',
 '1988',
 '1990',
 '1994',
 '1995',
 '1996',
 '1998',
 '1999',
 '19bn',
 '1a',
 '1pm',
 '20',
 '200',
 '2000',
 '2002',
 '2003',
 '2004',
 '2005',
 '2008',
 '200kg',
 '2011',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',


In [25]:
# transform() function will transform one or more documents to vectors
vector = BoWvectorizer.transform(documents)
array = vector.toarray()

In [26]:
j = 1
for i in array:
 print("doc",j," - ",i)
 j+=1

doc 1  -  [0 0 0 ... 0 0 0]
doc 2  -  [0 0 0 ... 0 0 0]
doc 3  -  [0 0 0 ... 0 0 0]
doc 4  -  [0 0 0 ... 0 0 0]
doc 5  -  [0 0 0 ... 0 0 0]
doc 6  -  [0 0 0 ... 0 0 0]
doc 7  -  [0 0 0 ... 0 0 0]
doc 8  -  [0 0 0 ... 0 0 0]
doc 9  -  [0 0 0 ... 0 0 0]
doc 10  -  [0 0 0 ... 0 0 0]
doc 11  -  [0 0 0 ... 0 0 0]
doc 12  -  [0 0 0 ... 0 0 0]
doc 13  -  [0 0 0 ... 0 0 0]
doc 14  -  [0 0 0 ... 0 0 0]
doc 15  -  [0 0 0 ... 0 0 0]
doc 16  -  [0 0 0 ... 0 0 0]
doc 17  -  [0 0 0 ... 0 0 0]
doc 18  -  [0 0 0 ... 0 0 0]
doc 19  -  [0 0 0 ... 0 0 0]
doc 20  -  [0 0 0 ... 0 0 0]
doc 21  -  [0 0 0 ... 0 0 0]
doc 22  -  [0 0 0 ... 0 0 0]
doc 23  -  [0 0 0 ... 0 0 0]
doc 24  -  [0 0 0 ... 0 0 0]
doc 25  -  [0 0 0 ... 0 0 0]
doc 26  -  [0 0 0 ... 0 0 0]
doc 27  -  [0 0 0 ... 0 0 0]
doc 28  -  [0 0 0 ... 0 0 0]
doc 29  -  [0 0 0 ... 0 0 0]
doc 30  -  [0 0 0 ... 0 0 0]
doc 31  -  [0 0 0 ... 0 0 0]
doc 32  -  [0 0 0 ... 0 0 0]
doc 33  -  [0 0 0 ... 0 0 0]
doc 34  -  [0 0 0 ... 0 0 0]
doc 35  -  [0 0 0 ... 0

doc 420  -  [0 0 0 ... 0 0 0]
doc 421  -  [0 0 0 ... 0 0 0]
doc 422  -  [0 0 0 ... 0 0 0]
doc 423  -  [0 0 0 ... 0 0 0]
doc 424  -  [0 0 0 ... 0 0 0]
doc 425  -  [0 0 0 ... 0 0 0]
doc 426  -  [0 0 0 ... 0 0 0]
doc 427  -  [0 0 0 ... 0 0 0]
doc 428  -  [0 0 0 ... 0 0 0]
doc 429  -  [0 0 0 ... 0 0 0]
doc 430  -  [0 0 0 ... 0 0 0]
doc 431  -  [0 0 0 ... 0 0 0]
doc 432  -  [0 0 0 ... 0 0 0]
doc 433  -  [0 0 0 ... 0 0 0]
doc 434  -  [0 0 0 ... 0 0 0]
doc 435  -  [0 0 0 ... 0 0 0]
doc 436  -  [0 0 0 ... 0 0 0]
doc 437  -  [0 0 0 ... 0 0 0]
doc 438  -  [0 0 0 ... 0 0 0]
doc 439  -  [0 0 0 ... 0 0 0]
doc 440  -  [0 0 0 ... 0 0 0]
doc 441  -  [0 0 0 ... 0 0 0]
doc 442  -  [0 0 0 ... 0 0 0]
doc 443  -  [0 0 0 ... 0 0 0]
doc 444  -  [0 0 0 ... 0 0 0]
doc 445  -  [0 0 0 ... 0 0 0]
doc 446  -  [0 0 0 ... 0 0 0]
doc 447  -  [0 0 0 ... 0 0 0]
doc 448  -  [0 0 0 ... 0 0 0]
doc 449  -  [0 0 0 ... 0 0 0]
doc 450  -  [0 0 0 ... 0 0 0]
doc 451  -  [0 0 0 ... 0 0 0]
doc 452  -  [0 0 0 ... 0 0 0]
doc 453  -

doc 742  -  [0 0 0 ... 0 0 0]
doc 743  -  [0 0 0 ... 0 0 0]
doc 744  -  [0 0 0 ... 0 0 0]
doc 745  -  [0 0 0 ... 0 0 0]
doc 746  -  [0 0 0 ... 0 0 0]
doc 747  -  [0 0 0 ... 0 0 0]
doc 748  -  [0 0 0 ... 0 0 0]
doc 749  -  [0 0 0 ... 0 0 0]
doc 750  -  [0 0 0 ... 0 0 0]
doc 751  -  [0 0 0 ... 0 0 0]
doc 752  -  [0 0 0 ... 0 0 0]
doc 753  -  [0 0 0 ... 0 0 0]
doc 754  -  [0 0 0 ... 0 0 0]
doc 755  -  [0 0 0 ... 0 0 0]
doc 756  -  [0 0 0 ... 0 0 0]
doc 757  -  [0 0 0 ... 0 0 0]
doc 758  -  [0 0 0 ... 0 0 0]
doc 759  -  [0 0 0 ... 0 0 0]
doc 760  -  [0 0 0 ... 0 0 0]
doc 761  -  [0 0 0 ... 0 0 0]
doc 762  -  [0 0 0 ... 0 0 0]
doc 763  -  [0 0 0 ... 0 0 0]
doc 764  -  [0 0 0 ... 0 0 0]
doc 765  -  [0 0 0 ... 0 0 0]
doc 766  -  [0 0 0 ... 0 0 0]
doc 767  -  [0 0 0 ... 0 0 0]
doc 768  -  [0 0 0 ... 0 0 0]
doc 769  -  [0 0 0 ... 0 0 0]
doc 770  -  [0 0 0 ... 0 0 0]
doc 771  -  [0 0 0 ... 0 0 0]
doc 772  -  [0 0 0 ... 0 0 0]
doc 773  -  [0 0 0 ... 0 0 0]
doc 774  -  [0 0 0 ... 0 0 0]
doc 775  -

doc 1080  -  [0 0 0 ... 0 0 0]
doc 1081  -  [0 0 0 ... 0 0 0]
doc 1082  -  [0 0 0 ... 0 0 0]
doc 1083  -  [0 0 0 ... 0 0 0]
doc 1084  -  [0 0 0 ... 0 0 0]
doc 1085  -  [0 0 0 ... 0 0 0]
doc 1086  -  [0 0 0 ... 0 0 0]
doc 1087  -  [0 0 0 ... 0 0 0]
doc 1088  -  [0 0 0 ... 0 0 0]
doc 1089  -  [0 0 0 ... 0 0 0]
doc 1090  -  [0 0 0 ... 0 0 0]
doc 1091  -  [0 0 0 ... 0 0 0]
doc 1092  -  [0 0 0 ... 0 0 0]
doc 1093  -  [0 0 0 ... 0 0 0]
doc 1094  -  [0 0 0 ... 0 0 0]
doc 1095  -  [0 0 0 ... 0 0 0]
doc 1096  -  [0 0 0 ... 0 0 0]
doc 1097  -  [0 0 0 ... 0 0 0]
doc 1098  -  [0 0 0 ... 0 0 0]
doc 1099  -  [0 0 0 ... 0 0 0]
doc 1100  -  [0 0 0 ... 0 0 0]
doc 1101  -  [0 0 0 ... 0 0 0]
doc 1102  -  [0 0 0 ... 0 0 0]
doc 1103  -  [0 0 0 ... 0 0 0]
doc 1104  -  [0 0 0 ... 0 0 0]
doc 1105  -  [0 0 0 ... 0 0 0]
doc 1106  -  [0 0 0 ... 0 0 0]
doc 1107  -  [0 0 0 ... 0 0 0]
doc 1108  -  [0 0 0 ... 0 0 0]
doc 1109  -  [0 0 0 ... 0 0 0]
doc 1110  -  [0 0 0 ... 0 0 0]
doc 1111  -  [0 0 0 ... 0 0 0]
doc 1112

doc 1395  -  [0 0 0 ... 0 0 0]
doc 1396  -  [0 0 0 ... 0 0 0]
doc 1397  -  [0 0 0 ... 0 0 0]
doc 1398  -  [0 0 0 ... 0 0 0]
doc 1399  -  [0 0 0 ... 0 0 0]
doc 1400  -  [0 0 0 ... 0 0 0]
doc 1401  -  [0 0 0 ... 0 0 0]
doc 1402  -  [0 0 0 ... 0 0 0]
doc 1403  -  [0 0 0 ... 0 0 0]
doc 1404  -  [0 0 0 ... 0 0 0]
doc 1405  -  [0 0 0 ... 0 0 0]
doc 1406  -  [0 0 0 ... 0 0 0]
doc 1407  -  [0 0 0 ... 0 0 0]
doc 1408  -  [0 0 0 ... 0 0 0]
doc 1409  -  [0 0 0 ... 0 0 0]
doc 1410  -  [0 0 0 ... 0 0 0]
doc 1411  -  [0 0 0 ... 0 0 0]
doc 1412  -  [0 0 0 ... 0 0 0]
doc 1413  -  [0 0 0 ... 0 0 0]
doc 1414  -  [0 0 0 ... 0 0 0]
doc 1415  -  [0 0 0 ... 0 0 0]
doc 1416  -  [0 0 0 ... 0 0 0]
doc 1417  -  [0 0 0 ... 0 0 0]
doc 1418  -  [0 0 0 ... 0 0 0]
doc 1419  -  [0 0 0 ... 0 0 0]
doc 1420  -  [0 0 0 ... 0 0 0]
doc 1421  -  [0 0 0 ... 0 0 0]
doc 1422  -  [0 0 0 ... 0 0 0]
doc 1423  -  [0 0 0 ... 0 0 0]
doc 1424  -  [0 0 0 ... 0 0 0]
doc 1425  -  [0 0 0 ... 0 0 0]
doc 1426  -  [0 0 0 ... 0 0 0]
doc 1427

doc 1691  -  [0 0 0 ... 0 0 0]
doc 1692  -  [0 0 0 ... 0 0 0]
doc 1693  -  [0 0 0 ... 0 0 0]
doc 1694  -  [0 0 0 ... 0 0 0]
doc 1695  -  [0 0 0 ... 0 0 0]
doc 1696  -  [0 0 0 ... 0 0 0]
doc 1697  -  [0 0 0 ... 0 0 0]
doc 1698  -  [0 0 0 ... 0 0 0]
doc 1699  -  [0 0 0 ... 0 0 0]
doc 1700  -  [0 0 0 ... 0 0 0]
doc 1701  -  [0 0 0 ... 0 0 0]
doc 1702  -  [0 0 0 ... 0 0 0]
doc 1703  -  [0 0 0 ... 0 0 0]
doc 1704  -  [0 0 0 ... 0 0 0]
doc 1705  -  [0 0 0 ... 0 0 0]
doc 1706  -  [0 0 0 ... 0 0 0]
doc 1707  -  [0 0 0 ... 0 0 0]
doc 1708  -  [0 0 0 ... 0 0 0]
doc 1709  -  [0 0 0 ... 0 0 0]
doc 1710  -  [0 0 0 ... 0 0 0]
doc 1711  -  [0 0 0 ... 0 0 0]
doc 1712  -  [0 0 0 ... 0 0 0]
doc 1713  -  [1 0 0 ... 0 0 0]
doc 1714  -  [1 0 0 ... 0 0 0]
doc 1715  -  [0 0 0 ... 0 0 0]
doc 1716  -  [0 0 0 ... 0 0 0]
doc 1717  -  [0 0 0 ... 0 0 0]
doc 1718  -  [0 0 0 ... 0 0 0]
doc 1719  -  [0 0 0 ... 0 0 0]
doc 1720  -  [0 0 0 ... 0 0 0]
doc 1721  -  [0 0 0 ... 0 0 0]
doc 1722  -  [0 0 0 ... 0 0 0]
doc 1723

doc 2068  -  [0 0 0 ... 0 0 0]
doc 2069  -  [0 0 0 ... 0 0 0]
doc 2070  -  [0 0 0 ... 0 0 0]
doc 2071  -  [0 0 0 ... 0 0 0]
doc 2072  -  [0 0 0 ... 0 0 0]
doc 2073  -  [0 0 0 ... 0 0 0]
doc 2074  -  [0 0 0 ... 0 0 0]
doc 2075  -  [0 0 0 ... 0 0 0]
doc 2076  -  [0 0 0 ... 0 0 0]
doc 2077  -  [0 0 0 ... 0 0 0]
doc 2078  -  [0 0 0 ... 0 0 0]
doc 2079  -  [0 0 0 ... 0 0 0]
doc 2080  -  [0 0 0 ... 0 0 0]
doc 2081  -  [0 0 0 ... 0 0 0]
doc 2082  -  [0 0 0 ... 0 0 0]
doc 2083  -  [0 0 0 ... 0 0 0]
doc 2084  -  [0 0 0 ... 0 0 0]
doc 2085  -  [0 0 0 ... 0 0 0]
doc 2086  -  [0 0 0 ... 0 0 0]
doc 2087  -  [0 0 0 ... 0 0 0]
doc 2088  -  [0 0 0 ... 0 0 0]
doc 2089  -  [0 0 0 ... 0 0 0]
doc 2090  -  [0 0 0 ... 0 0 0]
doc 2091  -  [0 0 0 ... 0 0 0]
doc 2092  -  [0 0 0 ... 0 0 0]
doc 2093  -  [0 0 0 ... 0 0 0]
doc 2094  -  [0 0 0 ... 0 0 0]
doc 2095  -  [0 0 0 ... 0 0 0]
doc 2096  -  [0 0 0 ... 0 0 0]
doc 2097  -  [0 0 0 ... 0 0 0]
doc 2098  -  [0 0 0 ... 0 0 0]
doc 2099  -  [0 0 0 ... 0 0 0]
doc 2100

doc 2425  -  [0 0 0 ... 0 0 1]
doc 2426  -  [0 0 0 ... 0 0 0]
doc 2427  -  [0 0 0 ... 0 0 0]
doc 2428  -  [0 0 0 ... 0 0 0]
doc 2429  -  [0 0 0 ... 0 0 0]
doc 2430  -  [0 0 0 ... 0 0 0]
doc 2431  -  [0 0 0 ... 0 0 0]
doc 2432  -  [0 0 0 ... 0 0 0]
doc 2433  -  [0 0 0 ... 0 0 0]
doc 2434  -  [0 0 0 ... 0 0 0]
doc 2435  -  [0 0 0 ... 0 0 0]
doc 2436  -  [0 0 0 ... 0 0 0]
doc 2437  -  [0 0 0 ... 0 0 0]
doc 2438  -  [0 0 0 ... 0 0 0]
doc 2439  -  [0 0 0 ... 0 0 0]
doc 2440  -  [0 0 0 ... 0 0 0]
doc 2441  -  [0 0 0 ... 0 0 0]
doc 2442  -  [0 0 0 ... 0 0 0]
doc 2443  -  [0 0 0 ... 0 0 0]
doc 2444  -  [0 0 0 ... 0 0 0]
doc 2445  -  [0 0 0 ... 0 0 0]
doc 2446  -  [0 0 0 ... 0 0 0]
doc 2447  -  [0 0 0 ... 0 0 0]
doc 2448  -  [0 0 0 ... 0 0 0]
doc 2449  -  [0 0 0 ... 0 0 0]
doc 2450  -  [0 0 0 ... 0 0 0]
doc 2451  -  [0 0 0 ... 0 0 0]
doc 2452  -  [0 0 0 ... 0 0 0]
doc 2453  -  [0 0 0 ... 0 0 0]
doc 2454  -  [0 0 0 ... 0 0 0]
doc 2455  -  [0 0 0 ... 0 0 0]
doc 2456  -  [0 0 0 ... 0 0 0]
doc 2457

doc 2740  -  [0 0 0 ... 0 0 0]
doc 2741  -  [0 0 0 ... 0 0 0]
doc 2742  -  [0 0 0 ... 0 0 0]
doc 2743  -  [0 0 0 ... 0 0 0]
doc 2744  -  [0 0 0 ... 0 0 0]
doc 2745  -  [0 0 0 ... 0 0 0]
doc 2746  -  [0 0 0 ... 0 0 0]
doc 2747  -  [0 0 0 ... 0 0 0]
doc 2748  -  [0 0 0 ... 0 0 0]
doc 2749  -  [0 0 0 ... 0 0 0]
doc 2750  -  [0 0 0 ... 0 0 0]
doc 2751  -  [0 0 0 ... 0 0 0]
doc 2752  -  [0 0 0 ... 0 0 0]
doc 2753  -  [0 0 0 ... 0 0 0]
doc 2754  -  [0 0 0 ... 0 0 0]
doc 2755  -  [0 0 0 ... 0 0 0]
doc 2756  -  [0 0 0 ... 0 0 0]
doc 2757  -  [0 0 0 ... 0 0 0]
doc 2758  -  [0 0 0 ... 0 0 0]
doc 2759  -  [0 0 0 ... 0 0 0]
doc 2760  -  [0 0 0 ... 0 0 0]
doc 2761  -  [0 0 0 ... 0 0 0]
doc 2762  -  [0 0 0 ... 0 0 0]
doc 2763  -  [0 0 0 ... 0 0 0]
doc 2764  -  [0 0 0 ... 0 0 0]
doc 2765  -  [0 0 0 ... 0 0 0]
doc 2766  -  [0 0 0 ... 0 0 0]
doc 2767  -  [0 0 0 ... 0 0 0]
doc 2768  -  [0 0 0 ... 0 0 0]
doc 2769  -  [0 0 0 ... 0 0 0]
doc 2770  -  [0 0 0 ... 0 0 0]
doc 2771  -  [0 0 0 ... 0 0 0]
doc 2772

doc 3034  -  [0 0 0 ... 0 0 0]
doc 3035  -  [0 0 0 ... 0 0 0]
doc 3036  -  [0 0 0 ... 0 0 0]
doc 3037  -  [0 0 0 ... 0 0 0]
doc 3038  -  [0 0 0 ... 0 0 0]
doc 3039  -  [0 0 0 ... 0 0 0]
doc 3040  -  [0 0 0 ... 0 0 0]
doc 3041  -  [0 0 0 ... 0 0 0]
doc 3042  -  [0 0 0 ... 0 0 0]
doc 3043  -  [0 0 0 ... 0 0 0]
doc 3044  -  [0 0 0 ... 0 0 0]
doc 3045  -  [0 0 0 ... 0 0 0]
doc 3046  -  [0 0 0 ... 0 0 0]
doc 3047  -  [0 0 0 ... 0 0 0]
doc 3048  -  [0 0 0 ... 0 0 0]
doc 3049  -  [0 0 0 ... 0 0 0]
doc 3050  -  [0 0 0 ... 0 0 0]
doc 3051  -  [0 0 0 ... 0 0 0]
doc 3052  -  [0 0 0 ... 0 0 0]
doc 3053  -  [0 0 0 ... 0 0 0]
doc 3054  -  [0 0 0 ... 0 0 0]
doc 3055  -  [0 0 0 ... 0 0 0]
doc 3056  -  [0 0 0 ... 0 0 0]
doc 3057  -  [0 0 0 ... 0 0 0]
doc 3058  -  [0 1 0 ... 0 0 0]
doc 3059  -  [0 0 0 ... 0 0 0]
doc 3060  -  [0 0 0 ... 0 0 0]
doc 3061  -  [0 0 0 ... 0 0 0]
doc 3062  -  [0 0 0 ... 0 0 0]
doc 3063  -  [0 0 0 ... 0 0 0]
doc 3064  -  [0 0 0 ... 0 0 0]
doc 3065  -  [0 0 0 ... 0 0 0]
doc 3066

doc 3418  -  [0 0 0 ... 0 0 0]
doc 3419  -  [0 0 0 ... 0 0 0]
doc 3420  -  [0 0 0 ... 0 0 0]
doc 3421  -  [0 0 0 ... 0 0 0]
doc 3422  -  [0 0 0 ... 0 0 0]
doc 3423  -  [0 0 0 ... 0 0 0]
doc 3424  -  [0 0 0 ... 0 0 0]
doc 3425  -  [0 0 0 ... 0 0 0]
doc 3426  -  [0 0 0 ... 0 0 0]
doc 3427  -  [0 0 0 ... 0 0 0]
doc 3428  -  [0 0 0 ... 0 0 0]
doc 3429  -  [0 0 0 ... 0 0 0]
doc 3430  -  [0 0 0 ... 0 0 0]
doc 3431  -  [0 0 0 ... 0 0 0]
doc 3432  -  [0 0 0 ... 0 0 0]
doc 3433  -  [0 0 0 ... 0 0 0]
doc 3434  -  [0 0 0 ... 0 0 0]
doc 3435  -  [0 0 0 ... 0 0 0]
doc 3436  -  [0 0 0 ... 0 0 0]
doc 3437  -  [0 0 0 ... 0 0 0]
doc 3438  -  [0 0 0 ... 0 0 0]
doc 3439  -  [0 0 0 ... 0 0 0]
doc 3440  -  [0 0 0 ... 0 0 0]
doc 3441  -  [0 0 0 ... 0 0 0]
doc 3442  -  [0 0 0 ... 0 0 0]
doc 3443  -  [0 0 0 ... 0 0 0]
doc 3444  -  [0 0 0 ... 0 0 0]
doc 3445  -  [0 0 0 ... 0 0 0]
doc 3446  -  [0 0 0 ... 0 0 0]
doc 3447  -  [0 0 0 ... 0 0 0]
doc 3448  -  [0 0 0 ... 0 0 0]
doc 3449  -  [0 0 0 ... 0 0 0]
doc 3450

In [27]:
# d. Create Tf-idf vectorization for each documents

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [29]:
tfidfvectorizer = TfidfVectorizer()     # create an object 

tfidfvectorizer = TfidfVectorizer(stop_words= 'english')   #-- stopwords can be removed

tfidfvectorizer.fit(documents)     # build vocabulary


TfidfVectorizer(stop_words='english')

In [30]:
tfidfvectorizer.vocabulary_

{'government': 3973,
 'july': 4935,
 'called': 1496,
 'energy': 3127,
 'sector': 7837,
 'debt': 2512,
 'situation': 8078,
 'state': 8367,
 'emergency': 3080,
 'mid': 5679,
 'year': 9774,
 'budget': 1416,
 'review': 7517,
 'finance': 3563,
 'minister': 5717,
 'ken': 4975,
 'ofori': 6172,
 'atta': 865,
 'castigated': 1604,
 'previous': 6847,
 'ndc': 5937,
 'entering': 3157,
 'obnoxious': 6118,
 'pay': 6445,
 'contracts': 2212,
 'signed': 8039,
 'obligate': 6114,
 'capacity': 1546,
 'need': 5948,
 'pays': 6450,
 'gh': 3888,
 'billion': 1166,
 'annually': 678,
 '300mw': 162,
 'installed': 4667,
 'country': 2305,
 'does': 2844,
 'consume': 2170,
 'sounded': 8217,
 'alarmed': 558,
 '2020': 114,
 'facing': 3404,
 'annual': 677,
 'excess': 3295,
 'gas': 3827,
 'charges': 1732,
 '550': 228,
 '850': 287,
 'million': 5695,
 'joynews': 4917,
 'business': 1461,
 'editor': 3010,
 'george': 3874,
 'wiafe': 9627,
 'said': 7690,
 'latest': 5126,
 'imf': 4476,
 'staff': 8332,
 'report': 7391,
 'expressi

In [31]:
tfidfvectorizer.get_feature_names()

['000',
 '003490',
 '01',
 '01190902',
 '021',
 '03',
 '032',
 '040',
 '04008957',
 '0500',
 '0517400',
 '06',
 '073',
 '08',
 '09099140121',
 '09099140122',
 '091810',
 '10',
 '100',
 '10005',
 '100m',
 '101',
 '1020',
 '104',
 '109',
 '11',
 '110',
 '111',
 '113',
 '1131',
 '114',
 '114059',
 '117',
 '118',
 '1197',
 '11th',
 '12',
 '120',
 '122',
 '125',
 '128',
 '12pm',
 '12th',
 '13',
 '130',
 '131',
 '1320',
 '133',
 '14',
 '140',
 '141',
 '144',
 '1460',
 '147',
 '15',
 '150',
 '155',
 '156',
 '158',
 '1590',
 '15kg',
 '16',
 '163',
 '165',
 '17',
 '170',
 '176',
 '18',
 '184',
 '186',
 '187',
 '19',
 '1911',
 '1919',
 '1920s',
 '1928',
 '1940',
 '1947',
 '1949',
 '195355',
 '1960s',
 '1965',
 '1966',
 '1967',
 '1969',
 '1972',
 '1973',
 '198',
 '1980',
 '1988',
 '1990',
 '1994',
 '1995',
 '1996',
 '1998',
 '1999',
 '19bn',
 '1a',
 '1pm',
 '20',
 '200',
 '2000',
 '2002',
 '2003',
 '2004',
 '2005',
 '2008',
 '200kg',
 '2011',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',


In [32]:
tfidfvectorizer.idf_

array([5.73845961, 8.47929964, 8.47929964, ..., 8.07383453, 8.07383453,
       8.47929964])

In [33]:
vectorized_text = tfidfvectorizer.transform(documents) # vectorize the text data
vectorized_text.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [34]:
import pandas as pd

In [35]:

vectorized_text = tfidfvectorizer.transform(documents) 
data = vectorized_text.toarray()
features = tfidfvectorizer.get_feature_names()
df = pd.DataFrame(data = data,columns = features)


In [36]:
df

000  003490   01  01190902  021   03  032  040  04008957  0500  ...  \
0     0.0     0.0  0.0       0.0  0.0  0.0  0.0  0.0       0.0   0.0  ...   
1     0.0     0.0  0.0       0.0  0.0  0.0  0.0  0.0       0.0   0.0  ...   
2     0.0     0.0  0.0       0.0  0.0  0.0  0.0  0.0       0.0   0.0  ...   
3     0.0     0.0  0.0       0.0  0.0  0.0  0.0  0.0       0.0   0.0  ...   
4     0.0     0.0  0.0       0.0  0.0  0.0  0.0  0.0       0.0   0.0  ...   
...   ...     ...  ...       ...  ...  ...  ...  ...       ...   ...  ...   
3536  0.0     0.0  0.0       0.0  0.0  0.0  0.0  0.0       0.0   0.0  ...   
3537  0.0     0.0  0.0       0.0  0.0  0.0  0.0  0.0       0.0   0.0  ...   
3538  0.0     0.0  0.0       0.0  0.0  0.0  0.0  0.0       0.0   0.0  ...   
3539  0.0     0.0  0.0       0.0  0.0  0.0  0.0  0.0       0.0   0.0  ...   
3540  0.0     0.0  0.0       0.0  0.0  0.0  0.0  0.0       0.0   0.0  ...   

      zoom  zoomed  zoonoses  zoonotic  zoya  zp2itaomof  zte  zuckerberg  \
0      0.0     0.0       0.0       0.0   0.0         0.0  0.0         0.0   
1      0.0     0.0       0.0       0.0   0.0         0.0  0.0         0.0   
2      0.0     0.0       0.0       0.0   0.0         0.0  0.0         0.0   
3      0.0     0.0       0.0       0.0   0.0         0.0  0.0         0.0   
4      0.0     0.0       0.0       0.0   0.0         0.0  0.0         0.0   
...    ...     ...       ...       ...   ...         ...  ...         ...   
3536   0.0     0.0       0.0       0.0   0.0         0.0  0.0         0.0   
3537   0.0     0.0       0.0       0.0   0.0         0.0  0.0         0.0   
3538   0.0     0.0       0.0       0.0   0.0         0.0  0.0         0.0   
3539   0.0     0.0       0.0       0.0   0.0         0.0  0.0         0.0   
3540   0.0     0.0       0.0       0.0   0.0         0.0  0.0         0.0   

      zurich  zweli  
0        0.0    0.0  
1        0.0    0.0  
2        0.0    0.0  
3        0.0    0.0  
4        0.0    0.0  
...      ...    ...  
3536     0.0    0.0  
3537     0.0    0.0  
3538     0.0    0.0  
3539     0.0    0.0  
3540     0.0    0.0  

[3541 rows x 9834 columns]

In [37]:
import numpy as np

In [38]:
 # def CosineSimilarity(x,y):
 #     similarity = np.dot(x,y)/(np.linalg.norm(x)*np.linalg.norm(y))
 #     return similarity



In [39]:

import math

In [40]:
def cosSimilar(v1,v2): 
    sum = 0
    lv1 = 0
    lv2 = 0
    for i in range(v1.shape[0]):
        sum += v1[i]*v2[i]
        lv1 += v1[i]*v1[i]
        lv2 += v2[i]*v2[i]
    dp = sum / (math.sqrt(lv1) * math.sqrt(lv2))
    return dp

In [41]:
def textToVector(a):
    vector = np.zeros(len(vocabulary1))
    for word in a.split():
        if word.lower() in vocabulary1:
            wordindex = vocabulary1.index(word.lower())
            vector[wordindex] +=1
        return vector

In [42]:
text_to_compare ="concerns about the purpose of government borrowings , whether it goes into consumption or into projects capable"
tv = textToVector(text_to_compare)
tv

array([0., 0., 0., ..., 0., 0., 0.])

In [43]:
docV

[array([1., 1., 1., ..., 0., 0., 0.]),
 array([1., 0., 0., ..., 0., 0., 0.]),
 array([1., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([1., 0., 0., ..., 0., 0., 0.]),
 array([1., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([1., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 

In [44]:
docV[1]

array([1., 0., 0., ..., 0., 0., 0.])

In [45]:
print(cosSimilar(docV[0],tv))

0.0


In [46]:
print(cosSimilar(docV[6],tv))

0.22360679774997896


In [47]:
for d in docV:
    print(cosSimilar(d,tv))

0.0
0.0
0.0
0.0
0.0
0.0
0.22360679774997896
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


<ipython-input-40-b71388556889>:9: RuntimeWarning: invalid value encountered in double_scalars
  dp = sum / (math.sqrt(lv1) * math.sqrt(lv2))



0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
nan
0.0
0.0
0.22360679774997896
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.24253562503633297
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
nan
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
