**Prabal Ghosh roll- AM.SC.P2CSC20040 assignment-4(bert base)-NLP**

In [3]:
!pip install transformers

     |████████████████████████████████| 2.8 MB 9.5 MB/s 
     |████████████████████████████████| 3.3 MB 37.5 MB/s 
     |████████████████████████████████| 895 kB 40.5 MB/s 
     |████████████████████████████████| 636 kB 41.7 MB/s 
     |████████████████████████████████| 52 kB 1.3 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [4]:
import torch


In [5]:
from transformers import BertTokenizer, BertModel
import matplotlib.pyplot as plt
%matplotlib inline
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [13]:
text = "How are you"
marked_text = "[CLS] " + text + " [SEP]"
word_token = tokenizer.tokenize(marked_text)
word_token = tokenizer.tokenize(marked_text)


In [14]:
word_token

['[CLS]', 'how', 'are', 'you', '[SEP]']

In [15]:
indexes = indexed_tokens = tokenizer.convert_tokens_to_ids(words)
indexes

[101, 7592, 102]

In [16]:
tokens_tensor = torch.tensor([indexes])

In [17]:
model = BertModel.from_pretrained('bert-base-uncased', output_hidden_states = True)
model.eval()

Downloading:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          

In [18]:
with torch.no_grad():
    outputs = model(tokens_tensor)
    hidden_states = outputs[2]

In [19]:
token_embeddings = torch.stack(hidden_states, dim=0)
token_embeddings = torch.squeeze(token_embeddings, dim=1)
token_embeddings = token_embeddings.permute(1,0,2)
token_embeddings.size()

torch.Size([3, 13, 768])

In [20]:
vec = torch.cat((token_embeddings[2][-1], token_embeddings[2][-2], token_embeddings[2][-3], token_embeddings[2][-4]), dim=0)

In [21]:
# Printing the tokens, the indexes, and the vector of the 3rd word
print(words)
print(indexes)
print(vec)

['[CLS]', 'hello', '[SEP]']
[101, 7592, 102]
tensor([ 0.5801,  0.0627, -0.2637,  ..., -0.0818, -0.0794,  0.0012])


In [22]:
text = "How are you"
marked_text = "[CLS] " + text + " [SEP]"


In [23]:
list(tokenizer.vocab.keys())[5000:5020]

['knight',
 'lap',
 'survey',
 'ma',
 '##ow',
 'noise',
 'billy',
 '##ium',
 'shooting',
 'guide',
 'bedroom',
 'priest',
 'resistance',
 'motor',
 'homes',
 'sounded',
 'giant',
 '##mer',
 '150',
 'scenes']

In [25]:
tokenize_text=tokenizer.tokenize(marked_text)
index=tokenizer.convert_tokens_to_ids(tokenize_text)
print(tokenize_text)

['[CLS]', 'how', 'are', 'you', '[SEP]']


In [26]:
for tup in zip(tokenize_text,index):
  print('{:<12}{:>6}'.format(tup[0],tup[1]))

[CLS]          101
how           2129
are           2024
you           2017
[SEP]          102


In [27]:
x=index
segment_id=[1] * len(x)
tokens_tensor=torch.tensor([x])
segments_tensor=torch.tensor([segment_id])
model=BertModel.from_pretrained('bert-base-uncased',output_hidden_states=True)
model.eval()
with torch.no_grad():
  output=model(tokens_tensor,segments_tensor)
  hidden_states=output[2]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [28]:
print("number of layers:",len(hidden_states)," (intial embeddings + 12 BERT layers)")
layer_i=0

print("number of batches:",len(hidden_states[layer_i]))
batch_i=0

print("number of tokens:",len(hidden_states[layer_i][batch_i]))
token_i=0

print("number of hidden:",len(hidden_states[layer_i][batch_i][token_i]))

number of layers: 13  (intial embeddings + 12 BERT layers)
number of batches: 1
number of tokens: 5
number of hidden: 768


In [29]:
token_i=4
layer_i=4
vec=hidden_states[layer_i][batch_i][token_i]
print(vec)


tensor([-3.4848e-02, -5.5445e-02,  1.8084e-02,  5.1881e-02, -7.6937e-02,
         3.8856e-02, -7.7454e-02, -4.2585e-02,  2.6679e-02, -3.2300e-02,
        -4.7979e-03, -3.6562e-02,  2.1911e-02, -7.1065e-02,  1.9376e-02,
         1.0454e-02,  2.6525e-02,  2.7375e-02,  1.7607e-02, -1.3907e-01,
        -1.1677e-01,  9.2281e-02, -4.6091e-02, -2.3518e-02,  2.4678e-02,
        -1.0990e-01, -3.5292e-02,  3.1506e-02,  8.5341e-02, -5.1755e-02,
        -1.4338e-03, -5.6999e-02, -4.8608e-02,  1.7851e-02, -6.0254e-02,
         1.8508e-02,  6.9309e-02, -2.4640e-02, -1.1276e-01,  1.5059e-01,
         1.9971e-02,  7.5701e-02, -4.7530e-02, -2.7077e-02,  1.7308e-02,
         1.8524e-02, -7.7898e-03,  8.6443e-02, -7.0682e-03, -2.3084e-02,
         1.2031e-01, -3.8707e-02, -9.0196e-02,  2.5942e-02, -1.7789e-02,
         3.2865e-02, -1.4709e-02,  1.2485e-01, -3.1997e-02,  5.7039e-02,
         3.4943e-02,  5.3410e-02,  6.4547e-02,  6.3537e-02, -2.4695e-02,
         7.5898e-03, -5.3114e-02,  2.7910e-02, -2.8

In [30]:
token_embeddings = torch.stack(hidden_states, dim=0)
token_embeddings.size()

torch.Size([13, 1, 5, 768])

In [31]:
token_embeddings = torch.squeeze(token_embeddings, dim=1)
token_embeddings.size()

torch.Size([13, 5, 768])

In [32]:
token_embeddings = token_embeddings.permute(1,0,2)
token_embeddings.size()

torch.Size([5, 13, 768])

In [40]:
token_i=4
layer_i=4
vec=token_embeddings[4][5]
print(vec)

tensor([-1.8227e-02, -4.2910e-02,  1.6701e-02,  3.4612e-02, -8.5313e-02,
         2.8706e-02, -8.3460e-02, -1.1525e-02, -1.4510e-03,  1.7898e-02,
         2.8223e-04, -3.4385e-02,  3.6087e-02, -5.4001e-02, -7.9072e-03,
         3.3181e-03,  2.6991e-02,  8.7893e-03,  1.6394e-02, -1.1996e-01,
        -1.4472e-01,  6.8441e-02, -4.6465e-02, -4.6643e-02,  1.2164e-02,
        -1.1538e-01, -3.0537e-02,  4.4716e-02,  6.6519e-02, -2.9548e-02,
        -2.5928e-03, -2.2766e-02, -6.2024e-02,  6.8006e-02, -4.3359e-02,
         1.8105e-02,  2.5950e-02, -5.3201e-02, -6.4123e-02,  1.4743e-01,
        -1.6395e-02,  7.9559e-02,  2.5700e-03, -1.9824e-02,  1.8365e-02,
         2.1278e-02, -3.8834e-03,  4.4578e-02, -2.5384e-02, -1.6087e-02,
         1.0199e-01, -1.7372e-02, -7.0836e-02,  7.3690e-02, -1.3692e-02,
         2.2107e-02, -3.1969e-02,  7.9626e-02, -2.0758e-02,  1.5290e-02,
         2.3002e-02,  1.2706e-02,  5.7112e-02,  2.6985e-02, -5.2756e-02,
        -4.1025e-02, -1.2373e-02,  1.7655e-02, -3.6

In [34]:
token_vecs_cat = []
for token in token_embeddings:
    cat_vec = torch.cat((token[-1], token[-2], token[-3], token[-4]), dim=0)
    token_vecs_cat.append(cat_vec)

In [38]:
from scipy.spatial.distance import cosine
print(text)
similar= 1 - cosine(token_vecs_cat[0][:5], token_vecs_cat[0][:5])
print("similarly",similar)
similar= 1 - cosine(token_vecs_cat[0][:5], token_vecs_cat[1][:5])
print("similarly",similar)
similar= 1 - cosine(token_vecs_cat[0][:5], token_vecs_cat[4][:5])
print("similarly",similar)



How are you
similarly 1.0
similarly -0.24621014297008514
similarly 0.6874715089797974
